import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import NextAuthProvider from '@/app/providers/NextAuth';
import { Session } from 'next-auth';
import { Header } from '@/components/layouts/header';
import clsx from 'clsx';
import GraphqlProvider from '@/app/providers/graphql';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session;
}>) {
  return (
    <html lang='ja'>
      <body className={clsx(inter.className)}>
        <NextAuthProvider session={session}>
          <GraphqlProvider>
            <Header />
            {children}
            <Toaster
              toastOptions={{
                classNames: {
                  loading: 'bg-white text-black border-gray-300',
                  error: 'bg-red-500 text-white border-red-500',
                  success: 'bg-green-500 text-white border-green-500',
                },
                duration: 2500,
              }}
            />
          </GraphqlProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
