import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import NextAuthProvider from '@/app/providers/NextAuth';
import { Session } from 'next-auth';
import { Header } from '@/components/layouts/header';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session;
}>) {
  return (
    <html lang='ja'>
      <body className={clsx(inter.className)}>
        <NextAuthProvider session={session}>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
