/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OC9ZIi5StAq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link';
import { SVGProps } from 'react';

export function Header() {
  return (
    <header className='flex items-center h-16 px-4 border-b w-full md:px-6'>
      <Link className='mr-4' href='/'>
        <PackageIcon className='h-6 w-6' />
        <span className='sr-only'>Acme Inc</span>
      </Link>
      <nav className='hidden space-x-4 md:flex flex-1 text-sm'>
        <Link className='font-medium hover:underline' href='/upload'>
          Upload
        </Link>
        <Link className='font-medium hover:underline' href='/input-attendance'>
          Input
        </Link>
      </nav>
    </header>
  );
}

function PackageIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='m7.5 4.27 9 5.15' />
      <path d='M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z' />
      <path d='m3.3 7 8.7 5 8.7-5' />
      <path d='M12 22V12' />
    </svg>
  );
}
